name: publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - run: mvn source:jar deploy -DaltDeploymentRepository=internal.repo::default::file://$PWD/target/repo
      - uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          SINGLE_COMMIT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: target/repo
          BRANCH: gh-pages
          CLEAN: true